apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: rasitirmak/spring
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: mysqlsvc
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: springdb
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  selector:
    app: spring
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30036
